/**
 * Private loopback bridge for the Python Agent sidecar.
 *
 * My DB stays owned by Electron main.  The sidecar can only ask for the
 * read-only library/history/trash snapshots or restore one trashed node; it
 * never receives the SQLite path, managed-file paths, or a general mutation
 * surface.  Tool results may be sent to a configured cloud model, so callers
 * still decide whether those My DB tools are enabled for that provider.
 */

import { randomBytes } from 'node:crypto'
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http'
import type { AddressInfo } from 'node:net'
import { myDbHistory, myDbRestoreNode, myDbState, myDbTrash } from './mydb.ts'

export interface MyDbAgentBridgeInfo {
  url: string
  token: string
}

let server: Server | null = null
let startPromise: Promise<MyDbAgentBridgeInfo> | null = null
let active: MyDbAgentBridgeInfo | null = null

function reply(response: ServerResponse, status: number, value: unknown): void {
  response.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store'
  })
  response.end(JSON.stringify(value))
}

function isAuthorised(request: IncomingMessage, token: string): boolean {
  const supplied = request.headers['x-aiso-mydb-agent-token']
  return typeof supplied === 'string' && supplied === token
}

async function readBody(request: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = []
  let size = 0
  for await (const chunk of request) {
    const value = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)
    size += value.length
    if (size > 8 * 1024) throw new Error('request body too large')
    chunks.push(value)
  }
  const raw = Buffer.concat(chunks).toString('utf8')
  if (!raw.trim()) return {}
  const parsed: unknown = JSON.parse(raw)
  if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error('invalid request body')
  return parsed as Record<string, unknown>
}

function isNodeId(value: unknown): value is string {
  // My DB IDs are UUIDs generated by Electron.  Keeping this strict ensures
  // the sidecar cannot smuggle SQL-like identifiers into the main process.
  return typeof value === 'string' && /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i.test(value)
}

function createBridgeServer(token: string): Server {
  return createServer((request, response) => {
    void (async () => {
      if (!isAuthorised(request, token)) {
        reply(response, 401, { error: 'unauthorised' })
        return
      }
      if (request.method === 'GET' && request.url === '/v1/library') {
        reply(response, 200, myDbState())
        return
      }
      if (request.method === 'GET' && request.url === '/v1/history') {
        reply(response, 200, myDbHistory())
        return
      }
      if (request.method === 'GET' && request.url === '/v1/trash') {
        reply(response, 200, myDbTrash())
        return
      }
      if (request.method === 'POST' && request.url === '/v1/restore-node') {
        const body = await readBody(request)
        if (!isNodeId(body.nodeId)) {
          reply(response, 400, { error: 'invalid node id' })
          return
        }
        reply(response, 200, { node: myDbRestoreNode(body.nodeId) })
        return
      }
      reply(response, 404, { error: 'not found' })
    })().catch(() => {
      if (!response.headersSent) reply(response, 400, { error: 'invalid My DB request' })
      else response.destroy()
    })
  })
}

export async function startMyDbAgentBridge(): Promise<MyDbAgentBridgeInfo> {
  if (active) return active
  if (startPromise) return startPromise
  const token = randomBytes(32).toString('hex')
  const candidate = createBridgeServer(token)
  startPromise = new Promise<MyDbAgentBridgeInfo>((resolve, reject) => {
    candidate.once('error', reject)
    candidate.listen(0, '127.0.0.1', () => {
      candidate.off('error', reject)
      const address = candidate.address() as AddressInfo | null
      if (!address || typeof address === 'string') {
        candidate.close()
        reject(new Error('My DB Agent bridge address is unavailable'))
        return
      }
      server = candidate
      active = { url: `http://127.0.0.1:${address.port}`, token }
      resolve(active)
    })
  }).finally(() => {
    startPromise = null
  })
  return startPromise
}

export function stopMyDbAgentBridge(): void {
  const current = server
  server = null
  active = null
  if (current) current.close()
}
